// Copyright 2017-2021 @earthwallet/ui-keyring authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@earthwallet/ui-keyring', version: '0.1.0' };
