const tokens = [
  {
    decimals: 8,
    fee: '1',
    feeTo: 'ait2m-zxajw-p2dgm-alxbb-yaqkq-s56u5-hwoi6-xq2ws-blrxy-i4en3-gae',
    id: 's24we-diaaa-aaaaa-aaaka-cai',
    name: 'Token5',
    owner: 'ait2m-zxajw-p2dgm-alxbb-yaqkq-s56u5-hwoi6-xq2ws-blrxy-i4en3-gae',
    symbol: 'TKN5',
    tokenCanisterId: 's24we-diaaa-aaaaa-aaaka-cai',
    totalSupply: '12910005000000',
  },
  {
    decimals: 8,
    fee: '1',
    feeTo: 'ait2m-zxajw-p2dgm-alxbb-yaqkq-s56u5-hwoi6-xq2ws-blrxy-i4en3-gae',
    id: 'sbzkb-zqaaa-aaaaa-aaaiq-cai',
    name: 'Token2',
    owner: 'ait2m-zxajw-p2dgm-alxbb-yaqkq-s56u5-hwoi6-xq2ws-blrxy-i4en3-gae',
    symbol: 'TKN2',
    tokenCanisterId: 'sbzkb-zqaaa-aaaaa-aaaiq-cai',
    totalSupply: '12900002000000',
  },
  {
    decimals: 8,
    fee: '1',
    feeTo: 'ait2m-zxajw-p2dgm-alxbb-yaqkq-s56u5-hwoi6-xq2ws-blrxy-i4en3-gae',
    id: 'sgymv-uiaaa-aaaaa-aaaia-cai',
    name: 'Token1',
    owner: 'ait2m-zxajw-p2dgm-alxbb-yaqkq-s56u5-hwoi6-xq2ws-blrxy-i4en3-gae',
    symbol: 'TKN1',
    tokenCanisterId: 'sgymv-uiaaa-aaaaa-aaaia-cai',
    totalSupply: '12910001000000',
  },
  {
    decimals: 8,
    fee: '1',
    feeTo: 'ait2m-zxajw-p2dgm-alxbb-yaqkq-s56u5-hwoi6-xq2ws-blrxy-i4en3-gae',
    id: 'si2b5-pyaaa-aaaaa-aaaja-cai',
    name: 'Token3',
    owner: 'ait2m-zxajw-p2dgm-alxbb-yaqkq-s56u5-hwoi6-xq2ws-blrxy-i4en3-gae',
    symbol: 'TKN3',
    tokenCanisterId: 'si2b5-pyaaa-aaaaa-aaaja-cai',
    totalSupply: '12900003000000',
  },
  {
    decimals: 8,
    fee: '1',
    feeTo: 'ait2m-zxajw-p2dgm-alxbb-yaqkq-s56u5-hwoi6-xq2ws-blrxy-i4en3-gae',
    id: 'sp3hj-caaaa-aaaaa-aaajq-cai',
    name: 'Token4',
    owner: 'ait2m-zxajw-p2dgm-alxbb-yaqkq-s56u5-hwoi6-xq2ws-blrxy-i4en3-gae',
    symbol: 'TKN4',
    tokenCanisterId: 'sp3hj-caaaa-aaaaa-aaajq-cai',
    totalSupply: '12910004000000',
  },
  {
    decimals: 8,
    fee: '0',
    feeTo: 'hw3bu-xgnkh-xfpbv-cw64b-za6ed-iwdtq-cdrhb-uykli-szniy-bohha-sae',
    id: 'tcvdh-niaaa-aaaaa-aaaoa-cai',
    name: '22',
    owner: 'hw3bu-xgnkh-xfpbv-cw64b-za6ed-iwdtq-cdrhb-uykli-szniy-bohha-sae',
    symbol: 'w',
    tokenCanisterId: 'tcvdh-niaaa-aaaaa-aaaoa-cai',
    totalSupply: '11111',
  },
  {
    decimals: 8,
    fee: '1',
    feeTo: 'tjpnz-kfh3h-es2ok-k7wp4-ieiad-qvntd-hd4k3-zxdlf-tg3of-l37zo-7ae',
    id: 'tfuft-aqaaa-aaaaa-aa`aoq-cai',
    name: 'abc3',
    owner: 'tjpnz-kfh3h-es2ok-k7wp4-ieiad-qvntd-hd4k3-zxdlf-tg3of-l37zo-7ae',
    symbol: 'abc3',
    tokenCanisterId: 'tfuft-aqaaa-aaaaa-aaaoq-cai',
    totalSupply: '1000000000',
  },
  {
    decimals: 8,
    fee: '1',
    feeTo: 'tjpnz-kfh3h-es2ok-k7wp4-ieiad-qvntd-hd4k3-zxdlf-tg3of-l37zo-7ae',
    id: 'tmxop-wyaaa-aaaaa-aaapa-cai',
    name: 'abc2',
    owner: 'tjpnz-kfh3h-es2ok-k7wp4-ieiad-qvntd-hd4k3-zxdlf-tg3of-l37zo-7ae',
    symbol: 'abc2',
    tokenCanisterId: 'tmxop-wyaaa-aaaaa-aaapa-cai',
    totalSupply: '1000000000',
  },
  {
    decimals: 8,
    fee: '1',
    feeTo: 'tjpnz-kfh3h-es2ok-k7wp4-ieiad-qvntd-hd4k3-zxdlf-tg3of-l37zo-7ae',
    id: 'vszjv-naaaa-aaaaa-aaa3q-cai',
    name: 'abc1',
    owner: 'tjpnz-kfh3h-es2ok-k7wp4-ieiad-qvntd-hd4k3-zxdlf-tg3of-l37zo-7ae',
    symbol: 'abc1',
    tokenCanisterId: 'vszjv-naaaa-aaaaa-aaa3q-cai',
    totalSupply: '1000000000',
  },
  {
    decimals: 8,
    fee: '1',
    feeTo: 'tjpnz-kfh3h-es2ok-k7wp4-ieiad-qvntd-hd4k3-zxdlf-tg3of-l37zo-7ae',
    id: 'vvypb-ayaaa-aaaaa-aaa3a-cai',
    name: 'abc4',
    owner: 'tjpnz-kfh3h-es2ok-k7wp4-ieiad-qvntd-hd4k3-zxdlf-tg3of-l37zo-7ae',
    symbol: 'abc4',
    tokenCanisterId: 'vvypb-ayaaa-aaaaa-aaa3a-cai',
    totalSupply: '1000000000',
  },
  {
    decimals: 8,
    fee: '1',
    feeTo: 'tjpnz-kfh3h-es2ok-k7wp4-ieiad-qvntd-hd4k3-zxdlf-tg3of-l37zo-7ae',
    id: 'w6ozc-gaaaa-aaaaa-aaarq-cai',
    name: 'xyz2',
    owner: 'tjpnz-kfh3h-es2ok-k7wp4-ieiad-qvntd-hd4k3-zxdlf-tg3of-l37zo-7ae',
    symbol: 'xyz2',
    tokenCanisterId: 'w6ozc-gaaaa-aaaaa-aaarq-cai',
    totalSupply: '1000000000',
  },
  {
    decimals: 8,
    fee: '0',
    feeTo: 'tekfw-kscip-kvny3-27g6f-dwvgm-42dbo-32qxl-mccan-5e4mh-zrfkb-5qe',
    id: 'wqmuk-5qaaa-aaaaa-aaaqq-cai',
    name: 'Token Dyno',
    owner: 'tekfw-kscip-kvny3-27g6f-dwvgm-42dbo-32qxl-mccan-5e4mh-zrfkb-5qe',
    symbol: 'TKD',
    tokenCanisterId: 'wqmuk-5qaaa-aaaaa-aaaqq-cai',
    totalSupply: '10000',
  },
  {
    decimals: 8,
    fee: '1',
    feeTo: 'tjpnz-kfh3h-es2ok-k7wp4-ieiad-qvntd-hd4k3-zxdlf-tg3of-l37zo-7ae',
    id: 'wzp7w-lyaaa-aaaaa-aaara-cai',
    name: 'xyz1',
    owner: 'tjpnz-kfh3h-es2ok-k7wp4-ieiad-qvntd-hd4k3-zxdlf-tg3of-l37zo-7ae',
    symbol: 'xyz1',
    tokenCanisterId: 'wzp7w-lyaaa-aaaaa-aaara-cai',
    totalSupply: '1000000000',
  },
  {
    decimals: 18,
    fee: '0',
    feeTo: 'gh575-elc5q-6s7j2-gjhta-r5qdr-jjojh-zqu6n-3g6ss-y5nmq-jytvs-nqe',
    id: 'xpeh5-6iaaa-aaaaa-aaaua-cai',
    name: 'NewTest',
    owner: 'gh575-elc5q-6s7j2-gjhta-r5qdr-jjojh-zqu6n-3g6ss-y5nmq-jytvs-nqe',
    symbol: 'NT',
    tokenCanisterId: 'xpeh5-6iaaa-aaaaa-aaaua-cai',
    totalSupply: '1100',
  },
];

export default tokens;
