// Copyright 2021 @earthwallet/extension-dapp authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@earthwallet/extension-dapp', version: '0.37.3-19' };
